apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinicapp
    spec:
      containers:
      - name: springapp
        image: dineshkumar55/sprintbootpetclinic:petclinicimage-BUILD_NUMBER
        ports:
        - containerPort: 8080
